#!/bin/bash

set -x
ext=""
with_subtitles() {
 ffmpeg -hide_banner -i "$file" $([[ "$2" ]] && echo "$2" || echo "") -vf "subtitles='$file'" -c:v libvpx -b:v 1500K "${file//$ext/.webm}"
}

without_subtitles() {
 ffmpeg -hide_banner -y -i "$file" $([[ "$2" ]] && echo "$2" || echo "") -c:v libvpx -b:v 1500K "${file//$ext/.webm}"
}

for file in "$1"; do
 ext=echo '$1' | grep -oP '\.\w+$';
 with_subtitles || without_subtitles;
done
