#!/bin/bash
if [ "$1" = "--help" ] || [ "$1" = "-help" ] || [ "$1" = "" ]; then
	echo "Usage: 	anime2webm input output-name [start-time] [end-time] [scale (ex: -1:480)] [args]
	------------------
	To get to the args, put letters instead of numbers in [start-time] [end-time] [scale]
	Example: anime2webm input output-name x x x [args]";
else
	read -p "Would you like to extract and install the fonts [Y/n]? " -n 1 -r CONT;
	echo;
		if [[ $CONT =~ ^[Yy]$ ]]; then
			extractfonts "$1";
		fi
	subid=$(mkvmerge -i "$1" | grep subtitles | awk -F" " '{print $3}');
    mkvextract tracks "$1" "$subid"subtitle.ass;
    regex="[0-9]+";
    ratio=$([[ "$5"  && $5 =~ $regex ]] && echo ", scale=$5" || echo "");
	ffmpeg -i "$1" $([[ "$3" &&  $3 =~ $regex ]] && echo "-ss $3" || echo "") $([[ "$4" &&  $4 =~ $regex ]] && echo "-to $4" || echo "") $([[ "${@:6}" ]] && echo "${@:6}" || echo "") -vf ass=subtitle.ass"$ratio" -c:v libvpx -crf 0 -b:v 1500K "$2".webm;
	rm ./subtitle.ass;
fi
